-- Create profiles table (links to auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create diets table (Pre-set diet plans)
create table public.diets (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create meals table (Items within a diet)
create table public.meals (
  id bigint generated by default as identity primary key,
  diet_id bigint references public.diets not null,
  name text not null,
  time_of_day text, -- e.g., "Breakfast", "09:00 AM"
  calories integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create daily_logs table (Tracking user progress)
create table public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  meal_id bigint references public.meals(id) not null,
  consumed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date default CURRENT_DATE -- To easily query "today's" logs
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.diets enable row level security;
alter table public.meals enable row level security;
alter table public.daily_logs enable row level security;

-- Policies (Simple for now: allow authenticated read/write for own data, read-only for common data)
create policy "Public profiles are viewable by everyone." on public.profiles for select using ( true );
create policy "Users can insert their own profile." on public.profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on public.profiles for update using ( auth.uid() = id );

create policy "Diets are viewable by everyone." on public.diets for select using ( true );
create policy "Meals are viewable by everyone." on public.meals for select using ( true );

create policy "Users can view their own logs." on public.daily_logs for select using ( auth.uid() = user_id );
create policy "Users can insert their own logs." on public.daily_logs for insert with check ( auth.uid() = user_id );

-- Insert some sample data
insert into public.diets (name, description) values
('Perda de Peso', 'Foco em baixa caloria e alta proteína'),
('Ganho de Massa', 'Hipertrofia com carboidratos complexos');

insert into public.meals (diet_id, name, time_of_day, calories) values
(1, 'Ovos Mexidos e Café', 'Café da Manhã', 300),
(1, 'Frango Grelhado com Salada', 'Almoço', 450),
(1, 'Iogurte Natural', 'Lanche da Tarde', 150),
(1, 'Peixe Assado com Legumes', 'Jantar', 400),
(2, 'Mingau de Aveia com Whey', 'Café da Manhã', 500),
(2, 'Arroz, Feijão e Carne Moída', 'Almoço', 700);
